<?php
if (!defined('ROUTES_DIR')) {
    define('CONTROLLERS_DIR', __DIR__ . DIRECTORY_SEPARATOR . 'controllers' . DIRECTORY_SEPARATOR);
    define('VIEWS_DIR', __DIR__ . DIRECTORY_SEPARATOR . 'views' . DIRECTORY_SEPARATOR);
    define('ROUTES_DIR', __DIR__ . DIRECTORY_SEPARATOR . 'routes' . DIRECTORY_SEPARATOR);
    define('CACHE_DIR', __DIR__ . DIRECTORY_SEPARATOR . 'cache' . DIRECTORY_SEPARATOR);
    define('SOURCE_DIR', __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR);
    define('CONFIG_DIR', __DIR__ . DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . 'core' . DIRECTORY_SEPARATOR . 'config' . DIRECTORY_SEPARATOR);
    define('SPEED_MODE_ROUTES_DIR', CONFIG_DIR . 'routes' . DIRECTORY_SEPARATOR);
    define('SCRIPTS_DIR', __DIR__ . DIRECTORY_SEPARATOR . 'scripts' . DIRECTORY_SEPARATOR);
}
